# Generated by Django 3.1.7 on 2021-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210311_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='operation',
            field=models.CharField(choices=[('INCOME', 'Доход'), ('EXPENSES', 'Расход')], default='EXPENSES', max_length=8),
        ),
        migrations.AddField(
            model_name='note',
            name='operation',
            field=models.CharField(choices=[('INCOME', 'Доход'), ('EXPENSES', 'Расход')], default='EXPENSES', max_length=8),
        ),
    ]
