# Generated by Django 3.1.7 on 2021-03-12 11:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210311_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='operation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
